import type { Metadata } from "next";
import PublicInfo from "@/app/public-info";

export const metadata: Metadata = { title: "Terms · Hog Wumbia" };

export default function TermsPage() {
  return (
    <PublicInfo title="A little humour. A few terms.">
      <p>Hog Wumbia is a free educational project: a weekly Owl Post feed of AI-generated captions and pictures, with Google sign-in, voting, and a weekly House Cup.</p>
      <h2>Using your account</h2>
      <p>Sign in with your own Google account. Upload only photos you have permission to use, and avoid uploading private information about other people.</p>
      <h2>Sending owls and voting</h2>
      <p>Captions and pictures are generated by AI from the week&apos;s prompt, the character you pick, and your optional twist. They can be wrong, strange, or unfunny, and they don&apos;t represent the views of the app or of any real person. Keep twists kind: don&apos;t use them to target real people, share private information, or try to make the AI produce hateful, sexual, or violent content. Each account can send a limited number of owls per day.</p>
      <p>Vote honestly with your own account. Creating extra accounts or automating votes to move the House Cup isn&apos;t allowed. Posts that break these terms may be removed.</p>
      <h2>Using the app</h2>
      <p>Do not attempt to access another person&apos;s profile or votes, interfere with sign-in, or disrupt the application. The characters are inspired by the Harry Potter books and remain the property of their respective owners; this project is not affiliated with or endorsed by them. Generated pictures carry Google&apos;s SynthID watermark.</p>
      <h2>An app in development</h2>
      <p>The app may change or become unavailable while the project is developed. There is no charge to sign in, send owls, or vote.</p>
      <p>For questions, contact <a href="mailto:realtristanrai@gmail.com">realtristanrai@gmail.com</a>. The privacy page explains how account, post, and vote information is used.</p>
    </PublicInfo>
  );
}
